# -*- coding: utf-8 -*-
"""distance_questions_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ntj1skXRv89XRD6XWllXRjieldmuZ4XM
"""

# Define parameters properties : board, pegs, gripper

from dataclasses import dataclass

@dataclass
class Board:
    height: float
    hole_depth: float
    spacing: float
    unit: str

@dataclass
class Peg:
    label: str
    width: float
    height: float
    x_coord: float
    y_coord: float
    unit: str



import math

# Helper conversions and distance calculations functions

def convert_units(value: float, from_unit: str, to_unit: str) -> float:
  # Conversion function that converts a value from one unit to another (mm <-> cm)
    if from_unit == to_unit:
        return value

    # convert everything to mm first
    if from_unit == 'cm':
        value_mm = value * 10
    elif from_unit == 'mm':
        value_mm = value
    else:
        raise ValueError(f"Unsupported unit: {from_unit}")

    # convert from mm to target unit (mm or cm)
    if to_unit == 'cm':
        return value_mm / 10
    elif to_unit == 'mm':
        return value_mm
    else:
        raise ValueError(f"Unsupported unit: {to_unit}")


def calculate_gt_distance(object_a: Peg, object_b: Peg, unit: str, include_height: bool = False) -> float:
    # Calculates the Euclidean distance between two pegs for ground truth

    # first, convert object_b's (x,y) coordinates to object_a's unit before calculating distance
    object_b_x_coord = convert_units(object_b.x_coord, object_b.unit, object_a.unit)
    object_b_y_coord = convert_units(object_b.y_coord, object_b.unit, object_a.unit)

    # calculate distance
    dx = object_a.x_coord - object_b_x_coord
    dy = object_a.y_coord - object_b_y_coord
    distance_sq = dx**2 + dy**2

    # for 3D distance, include dh
    if include_height:
        object_b_height = convert_units(object_b.height, object_b.unit, object_a.unit)
        dh = object_a.height - object_b_height
        distance_sq += dh**2
    distance = math.sqrt(distance_sq)

    # convert the calculated distance (which is in object_a.unit) to the desired 'unit
    return convert_units(distance, object_a.unit, unit)



import json
from pathlib import Path

# Question generator with distance calculations and image path
# For each question, returns a dictionary with: the question, the image path, and the ground truth

# Generates questions asking for the linear distance between the centers of two objects
def generate_distance_between_centers(image_path: str, object_a: Peg, object_b: Peg, unit: str):
    results = []
    # ground truth for distance between centers: always 2D, so include_height=False
    gt_value = calculate_gt_distance(object_a, object_b, unit, include_height=False)

    q1 = (
        f"Given that peg {object_a.label} is approximately {object_a.width}{object_a.unit} wide "
        f"and peg {object_b.label} is approximately {object_b.width}{object_b.unit} wide, "
        f"estimate the distance in {unit} between the centers of the two pegs. "
        f"Please provide a single numerical value (integer or float)."
    )
    results.append({'question': q1, 'image_path': image_path, 'ground_truth': f"{gt_value:.2f}{unit}"})

    q2 = (
        f"Given that peg {object_a.label} is approximately {object_a.width}{object_a.unit} wide and {object_a.height}{object_a.unit} tall, "
        f"and peg {object_b.label} is approximately {object_b.width}{object_b.unit} wide and {object_b.height}{object_b.unit} tall, "
        f"estimate the distance in {unit} between the centers of the two pegs. "
        f"Please provide a single numerical value (integer or float)."
    )
    results.append({'question': q2, 'image_path': image_path, 'ground_truth': f"{gt_value:.2f}{unit}"})
    return results


# Generates questions asking for the linear distance between the tops of two objects
def generate_distance_between_tops(image_path: str, object_a: Peg, object_b: Peg, unit: str):
    results = []
    # ground truth for distance between tops: always 3D, so include_height=True
    gt_value = calculate_gt_distance(object_a, object_b, unit, include_height=True)

    q1 = (
        f"Given that peg {object_a.label} is {object_a.height}{object_a.unit} tall "
        f"and peg {object_b.label} is {object_b.height}{object_b.unit} tall, "
        f"estimate the distance in {unit} between the top of peg {object_a.label} and the top of peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    results.append({'question': q1, 'image_path': image_path, 'ground_truth': f"{gt_value:.2f}{unit}"})

    q2 = (
        f"Given that peg {object_a.label} is {object_a.height}{object_a.unit} tall and {object_a.width}{object_a.unit} wide, "
        f"and peg {object_b.label} is {object_b.height}{object_b.unit} tall and {object_b.width}{object_b.unit} wide, "
        f"estimate the distance in {unit} between the top of peg {object_a.label} and the top of peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    results.append({'question': q2, 'image_path': image_path, 'ground_truth': f"{gt_value:.2f}{unit}"})
    return results


# Generates a question asking for distance between a large peg (sitting on distincts pegholes) and a small one
def generate_distance_given_large_peg(image_path: str, object_a: Peg, object_b: Peg, unit: str):
    results = []
    gt_value = calculate_gt_distance(object_a, object_b, unit, include_height=False)

    q1 = (
        f"Given that peg {object_a.label} is {object_a.width}{object_a.unit} wide, "
        f"estimate the straight line distance in {unit} between peg {object_a.label} and peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    results.append({'question': q1, 'image_path': image_path, 'ground_truth': f"{gt_value:.2f}{unit}"})
    return results


# Generates a question asking for distance between two pegs, given the board spacing
def generate_distance_given_board_spacing(image_path: str, object_a: Peg, object_b: Peg, board: Board, unit: str):
    results = []
    gt_value = calculate_gt_distance(object_a, object_b, unit, include_height=False)

    q1 = (
        f"Given that these pegboard holes are spaced {board.spacing}{board.unit} apart from one another, "
        f"estimate the distance in {unit} between peg {object_a.label} and peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    results.append({'question': q1, 'image_path': image_path, 'ground_truth': f"{gt_value:.2f}{unit}"})
    return results


# Generates a question asking for the distance given 1, or more specifications (attributes) of the given parameters
def generate_distance_mix_dimensions(image_path: str, object_a: Peg, object_b: Peg, board: Board, gripper_distance, unit: str):
    questions = []
    questions.append(
        f"Given that these pegboard holes are spaced {board.spacing}{board.unit} apart, "
        f"peg {object_a.label} is {object_a.width}{object_a.unit} wide, "
        f"estimate the linear distance in {unit} between peg {object_a.label} and peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    questions.append(
        f"Given that these pegboard holes are spaced {board.spacing}{board.unit} apart, "
        f"estimate the vertical distance in {unit} between the bases of the board and the pegs. "
        f"Please provide a single numerical value (integer or float)."
    )
    questions.append(
        f"Given that these pegboard holes are spaced {board.spacing}{board.unit} apart, "
        f"peg {object_a.label} is {object_a.height}{object_a.unit} tall, "
        f"peg {object_b.label} is {object_b.height}{object_b.unit} tall, "
        f"estimate the straight-line distance in {unit} between their tops. "
        f"Please provide a single numerical value (integer or float)."
    )
    questions.append(
        f"Given that these pegboard holes are spaced {board.spacing}{board.unit} apart, "
        f"the gripper's fingers are {gripper_distance}{unit} apart when open, "
        f"estimate the distance in {unit} between peg {object_a.label} and peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    questions.append(
        f"Given that these pegboard holes are spaced {board.spacing}{board.unit} apart, "
        f"estimate the width in {unit} of peg {object_a.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    questions.append(
        f"Given that the board is {board.height}{board.unit} tall, "
        f"estimate the height in {unit} of peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )

    gt_mix_dim_list = []
    gt_mix_dim_list.append(f"{calculate_gt_distance(object_a, object_b, unit, include_height=False):.2f}{unit}") # linear distance (2D)
    gt_mix_dim_list.append(f"{convert_units(board.height, board.unit, unit):.2f}{unit}") # converts vertical distance
    gt_mix_dim_list.append(f"{calculate_gt_distance(object_a, object_b, unit, include_height=True):.2f}{unit}") # straight-line distance of tops (3D)
    gt_mix_dim_list.append(f"{calculate_gt_distance(object_a, object_b, unit, include_height=False):.2f}{unit}") # distance with gripper (2D)
    gt_mix_dim_list.append(f"{convert_units(object_a.width, object_a.unit, unit):.2f}{unit}") # converts width
    gt_mix_dim_list.append(f"{convert_units(object_b.height, object_b.unit, unit):.2f}{unit}") # converts height
    results = []
    for q_idx, question in enumerate(questions):
        results.append({'question': question, 'image_path': image_path, 'ground_truth': gt_mix_dim_list[q_idx]})
    return results


# Generates a question asking for the distance when no clue/specification is given
def generate_distance_with_no_clue(image_path: str, object_a: Peg, object_b: Peg, unit: str):
    questions = []
    questions.append(
        f"Estimate the straight line distance in {unit} between peg {object_a.label} and peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    questions.append(
        f"Estimate the straight line distance in {unit} between the centers of peg {object_a.label} and peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )
    questions.append(
        f"Estimate the straight line distance in {unit} between the tops of peg {object_a.label} and peg {object_b.label}. "
        f"Please provide a single numerical value (integer or float)."
    )

    gt_no_clue_list = []
    gt_no_clue_list.append(f"{calculate_gt_distance(object_a, object_b, unit, include_height=False):.2f}{unit}") # assume 2D centers
    gt_no_clue_list.append(f"{calculate_gt_distance(object_a, object_b, unit, include_height=False):.2f}{unit}") # centers (2D)
    gt_no_clue_list.append(f"{calculate_gt_distance(object_a, object_b, unit, include_height=True):.2f}{unit}") # tops (3D)

    results = []
    for q_idx, question in enumerate(questions):
        results.append({'question': question, 'image_path': image_path, 'ground_truth': gt_no_clue_list[q_idx]})
    return results


# Generates a question asking to point to an object based on certain criteria
def generate_pointing_question(image_path: str, board: Board, gripper_distance, number_pegs, unit:str, available_pegs:list):
    questions = []
    results = []

    # question for largest peg and its pixel coordinates
    q1 = (
        f"Given the {number_pegs} pegs on the board, the pegboard holes spaced {board.spacing}{board.unit} apart, "
        f"point to the largest peg by its label and give its approximate pixel coordinates."
      )
    # find the largest peg by the width
    largest_peg = None
    if available_pegs:
        largest_peg = max(available_pegs, key=lambda peg: peg.width)
    if largest_peg:
        mask_filename = f"{Path(image_path).stem}_label_{largest_peg.label}_mask.png"
        ground_truth_data = {
            "label": largest_peg.label,
            "mask_path": (Path("masks") / mask_filename).as_posix(),
            "physical_xy_coordinates": [round(largest_peg.x_coord, 2), round(largest_peg.y_coord, 2)],
            "unit": largest_peg.unit
        }
        ground_truth_q1 = json.dumps(ground_truth_data)
    else:
        ground_truth_q1 = json.dumps({"status": "No pegs available"})
    results.append({'question': q1, 'image_path': image_path, 'ground_truth': ground_truth_q1})

    # question for smallest peg and its pixel coordinates
    q2 = (
        f"Given the {number_pegs} pegs on the board, the pegboard holes spaced {board.spacing}{board.unit} apart, "
        f"point to the smallest peg by its label and give its approximate pixel coordinates."
    )
    # find the smallest peg by the width
    smallest_peg = None
    if available_pegs:
        smallest_peg = min(available_pegs, key=lambda peg: peg.width)
    if smallest_peg:
        mask_filename_smallest = f"{Path(image_path).stem}_label_{smallest_peg.label}_mask.png"
        ground_truth_data_smallest = {
            "label": smallest_peg.label,
            "mask_path": (Path("masks") / mask_filename_smallest).as_posix(),
            "physical_xy_coordinates": [round(smallest_peg.x_coord, 2), round(smallest_peg.y_coord, 2)],
            "unit": smallest_peg.unit
        }
        ground_truth_q2 = json.dumps(ground_truth_data_smallest)
    else:
        ground_truth_q2 = json.dumps({"status": "No pegs available"})
    results.append({'question': q2, 'image_path': image_path, 'ground_truth': ground_truth_q2})

    return results



# Main testing block
# Create 'setups' dictionnaries list
# which include instances of pegs, boards, and other parameters

import random

# Build question blocks by printing the question, the image path, and the ground truth
def make_question(image_path, question, ground_truth=''):
    print(f"{question}")
    print(f"Image: {image_path}")
    print(f"Answer: {ground_truth}")
    print()

def main():
    setups = []
    gripper_dist = 8

    """
    # Setup : Basic Pegboard Example
    board = Board(height=0.4, hole_depth=0.2, spacing=0.5, unit='cm')
    peg_a = Peg(label='A', width=0.2, height=1, unit='cm', x_coord=0.0 * board1.spacing, y_coord=0.0 * board1.spacing)
    peg_b = Peg(label='B', width=0.2, height=1, unit='cm', x_coord=1.0 * board1.spacing, y_coord=0.0 * board1.spacing)
    peg_c = Peg(label='C', width=0.2, height=1.5, unit='cm', x_coord=0.0 * board1.spacing, y_coord=1.0 * board1.spacing)
    peg_d = Peg(label='D', width=0.2, height=1.5, unit='cm', x_coord=1.0 * board1.spacing, y_coord=1.0 * board1.spacing)
    peg_e = Peg(label='E', width=0.2, height=1.5, unit='cm', x_coord=2.0 * board1.spacing, y_coord=1.0 * board1.spacing)
    peg_f = Peg(label='F', width=2, height=5, unit='cm', x_coord=0.0 * board1.spacing, y_coord=2.0 * board1.spacing)
    peg_g = Peg(label='G', width=2, height=5, unit='cm', x_coord=1.0 * board1.spacing, y_coord=2.0 * board1.spacing)
    image_path = 'images/setup1-image.jpg'
    setups.append({
        'name': 'Setup 0: Basic Pegboard Example',
        'board': board,
        'pegs': {
            'a': peg1_a, 'b': peg1_b, 'c': peg1_c, 'd': peg1_d, 'e': peg1_e, 'f': peg1_f, 'g': peg1_g
        },
        'gripper_distance': gripper_dist,
        'image_path': image_path1,
        'number_pegs': 7 # for pointing questions
    })
    """

    # Add additional setups here
    # Setup 1A: Test set of similar pegs (70%-40% sizing) - side view
    board1 = Board(height=0.4, hole_depth=0.2, spacing=0.5, unit='cm')
    peg1_a = Peg(label='A', width=0.975, height=2.5, unit='cm', x_coord=4 * board1.spacing, y_coord=2 * board1.spacing)
    peg1_b = Peg(label='B', width=1.365, height=3.5, unit='cm', x_coord=13 * board1.spacing, y_coord=5 * board1.spacing)
    peg1_c = Peg(label='C', width=1.170, height=3, unit='cm', x_coord=25 * board1.spacing, y_coord=5 * board1.spacing)
    peg1_d = Peg(label='D', width=0.2, height=1, unit='cm', x_coord=18 * board1.spacing, y_coord=13 * board1.spacing)
    peg1_e = Peg(label='E', width=0.780, height=2, unit='cm', x_coord=5 * board1.spacing, y_coord=18 * board1.spacing)
    peg1_f = Peg(label='F', width=0.2, height=1, unit='cm', x_coord=11 * board1.spacing, y_coord=22 * board1.spacing)
    peg1_g = Peg(label='G', width=0.2, height=1, unit='cm', x_coord=21 * board1.spacing, y_coord=22 * board1.spacing)
    peg1_h = Peg(label='H', width=0.2, height=1.2, unit='cm', x_coord=34 * board1.spacing, y_coord=2.0 * board1.spacing)

    image_path_1A = 'images/setup1_side_view.jpg'
    setups.append({
        'name': 'Setup 1A: Side View ',
        'board': board1,
        'pegs': {
            'a': peg1_a, 'b': peg1_b, 'c': peg1_c, 'd': peg1_d, 'e': peg1_e, 'f': peg1_f, 'g': peg1_g, 'h': peg1_h
        },
        'gripper_distance': gripper_dist,
        'image_path': image_path_1A,
        'number_pegs': 8
    })

    # Setup 1B: Test set of similar pegs (70%-40% sizing) - mid view
    image_path_1B = 'images/setup1_mid_view.jpg'
    setups.append({
        'name': 'Setup 1B: Mid View ',
        'board': board1,
        'pegs': {
            'a': peg1_a, 'b': peg1_b, 'c': peg1_c, 'd': peg1_d, 'e': peg1_e, 'f': peg1_f, 'g': peg1_g, 'h': peg1_h
        },
        'gripper_distance': gripper_dist,
        'image_path': image_path_1B,
        'number_pegs': 8
    })

    # Setup 1C: Test set of similar pegs (70%-40% sizing) - overhead view
    image_path_1C = 'images/setup1_ovhd_view.jpg'
    setups.append({
        'name': 'Setup 1C: Overhead View ',
        'board': board1,
        'pegs': {
            'a': peg1_a, 'b': peg1_b, 'c': peg1_c, 'd': peg1_d, 'e': peg1_e, 'f': peg1_f, 'g': peg1_g, 'h': peg1_h
        },
        'gripper_distance': gripper_dist,
        'image_path': image_path_1C,
        'number_pegs': 8
    })


    # Setup 2A: smaller number of pegs with incremental distance - side view
    board2 = Board(height=0.4, hole_depth=0.2, spacing=0.5, unit='cm')
    peg2_a = Peg(label='A', width=2, height=5, unit='cm', x_coord=5 * board1.spacing, y_coord=3 * board1.spacing)
    peg2_b = Peg(label='B', width=1.560, height=4, unit='cm', x_coord=12 * board1.spacing, y_coord=18 * board1.spacing)
    peg2_c = Peg(label='C', width=0.975, height=2.5, unit='cm', x_coord=22 * board1.spacing, y_coord=5 * board1.spacing)
    peg2_d = Peg(label='D', width=0.585, height=1.5, unit='cm', x_coord=33 * board1.spacing, y_coord=14 * board1.spacing)
    peg2_e = Peg(label='E', width=0.2, height=1, unit='cm', x_coord=25 * board1.spacing, y_coord=22 * board1.spacing)
    image_path_2A = 'images/setup2_side_view.jpg'
    setups.append({
        'name': 'Setup 2A: Side View ',
        'board': board2,
        'pegs': {
            'a': peg2_a, 'b': peg2_b, 'c': peg2_c, 'd': peg2_d, 'e': peg2_e
        },
        'gripper_distance': gripper_dist,
        'image_path': image_path_2A,
        'number_pegs': 5
    })

    image_path_2B = 'images/setup2_mid_view.jpg'
    setups.append({
        'name': 'Setup 2B: Mid View ',
        'board': board2,
        'pegs': {
            'a': peg2_a, 'b': peg2_b, 'c': peg2_c, 'd': peg2_d, 'e': peg2_e
        },
        'gripper_distance': gripper_dist,
        'image_path': image_path_2B,
        'number_pegs': 5
    })

    image_path_2C = 'images/setup2_ovhd_view.jpg'
    setups.append({
        'name': 'Setup 2C: Overhead View ',
        'board': board2,
        'pegs': {
            'a': peg2_a, 'b': peg2_b, 'c': peg2_c, 'd': peg2_d, 'e': peg2_e
        },
        'gripper_distance': gripper_dist,
        'image_path': image_path_2C,
        'number_pegs': 5
    })


    global_question_counter = 48 # starting index for questions

    for setup in setups:
        print(f"--- Generating questions for {setup['name']} - Image: {setup['image_path']} ---")
        print()

        board = setup['board']
        image_path = setup['image_path']
        gripper_distance = setup['gripper_distance']
        number_pegs = setup['number_pegs']
        pegs = setup['pegs']

        available_pegs = [peg for peg_label, peg in pegs.items() if peg is not None] # retrieve pegs from the pegs dictionary

        # Get image dimensions for pixel coordinates calculation (pointing question)
        # img_width, img_height = get_image_dimensions(image_path)

        print("\t1.Distance Between Centers:")
        if len(available_pegs) >= 2:
            peg1, peg2 = random.sample(available_pegs, 2)
            center_questions = generate_distance_between_centers(image_path, peg1, peg2, board.unit)
            for q_dict in center_questions:
                make_question(q_dict['image_path'], f"Q{global_question_counter}: {q_dict['question']}", ground_truth=q_dict['ground_truth'])
                global_question_counter += 1

        print("\t2.Distance Between Tops:")
        if len(available_pegs) >= 2:
            peg1, peg2 = random.sample(available_pegs, 2)
            tops_questions = generate_distance_between_tops(image_path, peg1, peg2, board.unit)
            for q_dict in tops_questions:
                make_question(q_dict['image_path'], f"Q{global_question_counter}: {q_dict['question']}", ground_truth=q_dict['ground_truth'])
                global_question_counter += 1

        print("\t3.Distance Given Large Peg:")
        if len(available_pegs) >= 2:
            # filter for large and small pegs based on Setup 1 dimensions
            large_pegs = [p for p in available_pegs if p.width >= 0.7 and p.height >= 2]
            small_pegs = [p for p in available_pegs if p.width <= 0.5 and p.height <= 1.4]

            if large_pegs and small_pegs:
                peg1 = random.choice(large_pegs)
                peg2 = random.choice(small_pegs)
            else:
                # use the general random selection if specific large/small pegs do not exist
                peg1, peg2 = random.sample(available_pegs, 2)

            large_peg_questions = generate_distance_given_large_peg(image_path, peg1, peg2, board.unit)
            for q_dict in large_peg_questions:
                make_question(q_dict['image_path'], f"Q{global_question_counter}: {q_dict['question']}", ground_truth=q_dict['ground_truth'])
                global_question_counter += 1

        print("\t4.Distance Given Board Spacing:")
        if len(available_pegs) >= 2:
            peg1, peg2 = random.sample(available_pegs, 2)
            board_spacing_questions = generate_distance_given_board_spacing(image_path, peg1, peg2, board, board.unit)
            for q_dict in board_spacing_questions:
                make_question(q_dict['image_path'], f"Q{global_question_counter}: {q_dict['question']}", ground_truth=q_dict['ground_truth'])
                global_question_counter += 1

        print("\t5.Distance Mix Dimensions:")
        if len(available_pegs) >= 2:
             peg1, peg2 = random.sample(available_pegs, 2)
             mix_dim_questions = generate_distance_mix_dimensions(image_path, peg1, peg2, board, gripper_distance, board.unit)
             for q_dict in mix_dim_questions:
                make_question(q_dict['image_path'], f"Q{global_question_counter}: {q_dict['question']}", ground_truth=q_dict['ground_truth'])
                global_question_counter += 1

        print("\t6.Distance No Clue Question:")
        if len(available_pegs) >= 2:
            peg1, peg2 = random.sample(available_pegs, 2)
            no_clue_questions = generate_distance_with_no_clue(image_path, peg1, peg2, board.unit)
            for q_dict in no_clue_questions:
                make_question(q_dict['image_path'], f"Q{global_question_counter}: {q_dict['question']}", ground_truth=q_dict['ground_truth'])
                global_question_counter += 1

        print("\t7.Pointing Question:")
        if gripper_distance:
            pointing_questions = generate_pointing_question(image_path, board, gripper_distance, number_pegs, board.unit, available_pegs)
            for q_dict in pointing_questions:
                make_question(q_dict['image_path'], f"Q{global_question_counter}: {q_dict['question']}", ground_truth=q_dict['ground_truth'])
                global_question_counter += 1

        print()

    print(f"Total generated questions (with new setups): {global_question_counter - 48}")

if __name__ == "__main__":
    main()